const policyPages={
  privacy:{title:"Privacy Policy",intro:"How VK Nutrition handles customer information when you browse, create an account, place an order, or contact support.",sections:[
    ["Information We Collect","We may collect information you provide directly, including your name, email address, mobile number, delivery address, account details, messages to support, and information required to fulfil your order. Order and transaction records may include products ordered, order value, delivery updates and payment status."],
    ["How We Use Information","VK Nutrition uses this information to create and manage accounts, process and deliver orders, provide customer support, prevent misuse of the website, communicate important order updates, and improve the store experience."],
    ["Payments and Service Providers","Payments may be processed by third-party payment providers. VK Nutrition should not directly store sensitive card credentials unless its live implementation is specifically designed and compliant to do so. We may also use third parties for hosting, authentication, payments, analytics, communications and delivery services, only as needed to operate the store."],
    ["Cookies and Local Storage","This website may use cookies or local storage to remember session, appearance, cart, wishlist and other website preferences. You can control or clear these through your browser settings, but some website features may then work differently."],
    ["Security and Retention","We use reasonable administrative and technical measures appropriate to the services in use. No online method is completely risk-free. Information is retained only for as long as reasonably necessary for orders, support, legal obligations, dispute resolution and legitimate business records."],
    ["Your Choices and Policy Changes","You may ask us to update account information or raise privacy concerns using the contact details below. We may revise this policy when our services or legal obligations change; the current version will be published on this page."],
    ["Privacy Contact","For privacy questions, contact <span class=\"editable\">Store owner: support@vknutrtions.com>." ]
  ]},
  terms:{title:"Terms & Conditions",intro:"These terms govern use of the VK Nutrition website and purchases made through it.",sections:[
    ["Acceptance and Eligibility","By using this website or placing an order, you agree to these Terms & Conditions. You must provide accurate information and be legally able to enter into a purchase transaction under applicable Indian law."],
    ["Accounts and Customer Responsibilities","You are responsible for keeping account and contact details current, protecting account access, and providing a complete delivery address. Do not use the website for unlawful, fraudulent or disruptive activity."],
    ["Products, Availability and Pricing","We aim to present product descriptions, images, pack sizes and prices accurately. Product availability, pricing and offers can change. Product information is not a substitute for medical advice; please review the product label and consult an appropriate professional where needed."],
    ["Orders, Payments and Acceptance","An order request is subject to acceptance. VK Nutrition may need to decline or cancel an order due to availability, pricing or technical issues, suspected misuse, or legal requirements. Payment transactions may be handled by an independent payment provider under its own terms."],
    ["Shipping, Returns and Refunds","Shipping and delivery are governed by our <a href=\"../shipping-delivery-policy/\">Shipping & Delivery Policy</a>. Cancellations and refunds are governed by our <a href=\"../cancellation-refund-policy/\">Cancellation & Refund Policy</a>."],
    ["Intellectual Property and Third Parties","VK Nutrition content, branding and website materials may not be copied or misused without permission. Links or services provided by third parties are subject to their own terms and privacy practices."],
    ["Liability and Changes","To the extent permitted by law, VK Nutrition is not liable for indirect or consequential losses arising from website use or delayed delivery. These terms may change from time to time; continued use after publication means you accept the updated terms."],
    ["Governing Law and Support","These terms are governed by applicable laws of India. Jurisdiction: <span class=\"editable\">Store owner: add city and state before publishing</span>. For support, use our <a href=\"../contact-us/\">Contact Us</a> page." ]
  ]},
  shipping:{title:"Shipping & Delivery Policy",intro:"Information about order processing, delivery and the prepaid free-delivery offer.",sections:[
    ["Order Processing","Orders are processed after successful order confirmation. Processing may take longer during high demand, holidays, address verification or product availability checks. <span class=\"editable\">Store owner: add normal order-processing timeframe</span>."],
    ["Delivery Locations and Charges","Delivery availability depends on the delivery address and serviceability at checkout. Shipping charges, if any, are shown before payment. <span class=\"editable\">Store owner: add serviceable locations/PIN-code rules and standard shipping charges</span>."],
    ["Prepaid Free Delivery Offer","VK Nutrition currently promotes “Prepay your order and get FREE delivery.” This applies only to prepaid orders that are confirmed as eligible at checkout. The minimum order value, serviceable locations, exclusions and offer period are not configured in this project and must be added by the store owner before publishing."],
    ["Estimated Delivery and Tracking","Estimated delivery timing depends on the address, courier availability and order processing. <span class=\"editable\">Store owner: add estimated delivery timeline</span>. Where tracking is available, customers can access updates through their order history or tracking reference."],
    ["Delays, Addresses and Failed Delivery","Delays can occur because of address issues, weather, local restrictions or delivery-partner operations. Customers must provide a complete, correct address and reachable mobile number. Additional delivery attempts or address corrections depend on the delivery partner’s process."],
    ["Damaged or Missing Packages","If a package arrives visibly damaged, tampered with, incomplete or missing, contact VK Nutrition promptly and keep relevant photos, unboxing evidence and order details. We will review the issue according to our <a href=\"../cancellation-refund-policy/\">Cancellation & Refund Policy</a>."],
    ["Delivery Support","For delivery help, use our <a href=\"../contact-us/\">Contact Us</a> page and include your order number." ]
  ]},
  refunds:{title:"Cancellation & Refund Policy",intro:"How cancellation, return, replacement and refund requests are handled for VK Nutrition orders.",sections:[
    ["Cancelling an Order","You may request cancellation before dispatch by contacting VK Nutrition with your order number. Cancellation after dispatch may not be possible. <span class=\"editable\">Store owner: 91+ 84259 20360</span>."],
    ["Consumable Product Returns","For hygiene and product-safety reasons, opened, used, unsealed or tampered consumable products are normally not eligible for return or refund, except where required by applicable law or where VK Nutrition confirms an issue with the order."],
    ["Eligible Issues","Please contact us if you receive the wrong product, a damaged or tampered package, an incomplete order, or an item materially different from your confirmed order. Clear photos of the outer package, product, seal and order label may be reasonably required to review the request."],
    ["Refund Review and Method","After reviewing an eligible request, VK Nutrition may offer replacement, store resolution or a refund as appropriate. Approved refunds are generally returned through the original payment method where possible. <span class=\"editable\">Store owner: add return-request window and refund-processing timeframe</span>."],
    ["Non-returnable Situations","Requests may not be accepted for change of mind after a consumable product is opened, for damage caused after delivery, or where the product seal is broken by the customer, subject to applicable consumer law."],
    ["How to Request Help","Use our <a href=\"../contact-us/\">Contact Us</a> page with your name, order number, product name, issue description and supporting photos where relevant." ]
  ]}
};
const key=document.body.dataset.policy;const page=policyPages[key];const main=document.querySelector('#policyMain');
function slug(value){return value.toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
function renderSections(sections){return sections.map(([heading,content])=>`<section class="policy-section" id="${slug(heading)}"><h2>${heading}</h2><p>${content}</p></section>`).join('')}
function renderStandard(){document.querySelector('#policyTitle').textContent=page.title;document.querySelector('#policyIntro').textContent=page.intro;const toc=page.sections.map(([heading])=>`<a href="#${slug(heading)}">${heading}</a>`).join('');main.innerHTML=`<aside class="policy-toc"><strong>On this page</strong><nav>${toc}</nav></aside><article class="policy-content">${renderSections(page.sections)}</article>`}
function renderContact(){document.querySelector('#policyTitle').textContent='Contact Us';document.querySelector('#policyIntro').textContent='Contact VK Nutrition for product, order, delivery and support questions.';main.innerHTML=`<article class="policy-content"><section class="policy-section"><h2>Customer Support</h2><div class="contact-grid"><div class="contact-card"><h3>Support Email</h3><p><span class="editable">support@vknutrtions.coml</span></p></div><div class="contact-card"><h3>Support Phone</h3><p><span class="editable">91+ 84259 20360</span></p></div><div class="contact-card"><h3>Store Address</h3><p><span class="editable">Samadhan Society, om, Chandavarkar Rd, opp. Borivali West, Vazira, Borivali, Mumbai, Maharashtra 400091</span></p></div><div class="contact-card"><h3>Support Hours</h3><p><span class="editable">10 AM to 9 PM </span></p></div></div></section><section class="policy-section"><h2>Send a Message</h2><p>Please include your order number when your enquiry relates to an order.</p><form id="contactForm" class="contact-form" novalidate><div class="contact-field"><label for="contactName">Name</label><input id="contactName" required autocomplete="name"></div><div class="contact-field"><label for="contactEmail">Email</label><input id="contactEmail" type="email" required autocomplete="email"></div><div class="contact-field"><label for="contactMobile">Mobile Number</label><input id="contactMobile" inputmode="tel" autocomplete="tel"></div><div class="contact-field"><label for="contactOrder">Order Number (optional)</label><input id="contactOrder"></div><div class="contact-field full"><label for="contactSubject">Subject</label><input id="contactSubject" required></div><div class="contact-field full"><label for="contactMessage">Message</label><textarea id="contactMessage" required></textarea></div><button class="policy-submit" type="submit">Send Message</button><p class="form-status" id="contactStatus" aria-live="polite"></p></form></section></article>`;document.querySelector('#contactForm').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;if(!form.checkValidity()){form.reportValidity();return}document.querySelector('#contactStatus').textContent='This contact form needs a configured support inbox before it can deliver messages. Please add the support email above before publishing.'})}
function applyTheme(theme){const next=theme==='dark'?'dark':'light';document.documentElement.dataset.theme=next;localStorage.setItem('vk-theme',next);const btn=document.querySelector('#policyTheme');if(btn){btn.textContent=next==='dark'?'☀':'🌙';btn.setAttribute('aria-label',next==='dark'?'Switch to light mode':'Switch to dark mode')}}
applyTheme(localStorage.getItem('vk-theme')||'light');document.querySelector('#policyTheme').addEventListener('click',()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));if(key==='contact')renderContact();else renderStandard();
